// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsApi.Infrastructure;

#nullable disable

namespace NewsApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240131170856_Add statistics table and seeded it")]
    partial class Addstatisticstableandseededit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsApi.Core.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 37,
                            Name = "Tim",
                            Surname = "Bontemps"
                        },
                        new
                        {
                            Id = 2,
                            Age = 39,
                            Name = "Bill",
                            Surname = "Barnwell"
                        },
                        new
                        {
                            Id = 3,
                            Age = 42,
                            Name = "Laura",
                            Surname = "Sanders"
                        },
                        new
                        {
                            Id = 4,
                            Age = 53,
                            Name = "Bruce",
                            Surname = "Bower"
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            Name = "Aadel",
                            Surname = "Chaudhuri"
                        },
                        new
                        {
                            Id = 6,
                            Age = 44,
                            Name = "Katharine",
                            Surname = "Lang"
                        });
                });

            modelBuilder.Entity("NewsApi.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Category about sport",
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Category about science",
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Category about medicine",
                            Name = "Medicine"
                        });
                });

            modelBuilder.Entity("NewsApi.Core.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Description = "Our insiders makes the moves they think NBA GMs should be making ahead of Feb. 8, including a big deal to shake up the Lakers.",
                            Text = "The 2024 NBA trade deadline is fast approaching, and while some teams have already been active, there are still plenty of others who need to make moves.\r\n\r\nWith that in mind, we asked our experts to come up with trades they want to see at the Feb. 8 deadline, whether it's a smaller deal to help a contender fill a hole, or a bigger move that could shake up the entire league.\r\n\r\nThey worked their magic in the ESPN Trade Machine and came up with six deals they want to see over the next 10 days -- and yes, the Los Angeles Lakers are involved.",
                            Title = "Six big NBA trades we want to see before the deadline",
                            TotalVisits = 0
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 1,
                            Description = "The Lions surrendered a 17-point second-half lead, while the vaunted Ravens scored just 10 points. Here's how the 49ers and Chiefs won.",
                            Text = "Chiefs-Ravens was a slow burn, as Kansas City got out to an early lead and held onto it throughout. Baltimore got closer and closer to competing as the game went along, but mistakes at the wrong time shut down its chances. One year after he was the leading receiver for the Chiefs in the AFC Championship Game, Marquez Valdes-Scantling hauled in a 32-yard bomb on third-and-9 to break the Ravens and send the Chiefs back to the Super Bowl.\r\n\r\nLions-49ers was a slugfest, and could also be accurately described as a rope-a-dope. Detroit dominated early and jumped out to a 17-point lead, only for San Francisco to claw its way back in the second half. In a four-minute window, the 49ers pounced. They stopped the Lions on fourth down, scored a touchdown, forced a fumble and scored again to tie the game. While Detroit threatened later in the game, another failed fourth-down try put San Francisco in the driver's seat, sealing a Super Bowl LIV rematch against the Chiefs.",
                            Title = "Barnwell: The truth behind Detroit's disastrous second half and Baltimore's botched Super Bowl chance",
                            TotalVisits = 0
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 2,
                            Description = "Alzheimer’s isn’t contagious. But contaminated growth hormone injections caused early-onset Alzheimer’s in some recipients, a new study suggests.",
                            Text = "Under extremely rare circumstances, it appears that Alzheimer’s disease can be transmitted between people. Five people who received contaminated injections of a growth hormone as children went on to develop Alzheimer’s unusually early, researchers report January 29 in Nature Medicine.",
                            Title = "Under very rare conditions, Alzheimer’s disease may be transmitted",
                            TotalVisits = 0
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 2,
                            Description = "New climate data for ancient Italy point to temperature and rainfall influences on past infectious disease outbreaks.",
                            Text = "For those who enjoy pondering the Roman Empire’s rise and fall — you know who you are — consider the close link between ancient climate change and infectious disease outbreaks. Periods of increasingly cooler temperatures and rainfall declines coincided with three pandemics that struck the Roman Empire, historian Kyle Harper and colleagues report January 26 in Science Advances. Reasons for strong associations between cold, dry phases and those disease outbreaks are poorly understood. ",
                            Title = "Cold, dry snaps accompanied three plagues that struck the Roman Empire",
                            TotalVisits = 0
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 3,
                            Description = "A lack of funding, mentorship, and compensation for clinician-researchers could threaten America's standing as the world leader in biomedicine.",
                            Text = "Recent reporting has shown that the number of physician-scientists — doctors who both practice medicine and perform scientific research — in the United States is dropping rapidly. That's a problem, because physician-scientists are uniquely equipped to make scientific discoveries in the laboratory and translate them to the clinic. Indeed, many of the discoveries that have transformed medicine for the better were made by physician-scientists. For example, Jonas Salk developed the polio vaccine, Timothy Ley sequenced the first cancer genome, and Anthony Fauci coordinated public health responses to both the HIV/AIDS and COVID-19 pandemics. Indicative of their sheer impact, at least a third and as many as half of all Nobel Prizes and Lasker Awards in physiology/medicine have gone to physician-scientists.",
                            Title = "The Emerging Physician-Scientist Crisis in America",
                            TotalVisits = 0
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            CategoryId = 3,
                            Description = "There is some evidence — both scientific and anecdotal — that some diets may help with the management of long COVID symptoms. Which...",
                            Text = "For many people, particularly following vaccination, infection with SARS-CoV-2, the virus that causes COVID-19, resolves within a few days. But for others, it results in long COVID, a variety of often debilitating symptoms that persist for weeks, months or even years. Why this happens in some is unclear, and there are currently no effective treatments. Some experts believe diet could be key to symptom management. What is the evidence for this?",
                            Title = "Could some diets help manage long COVID?",
                            TotalVisits = 0
                        });
                });

            modelBuilder.Entity("NewsApi.Core.Entities.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<string>("VisitorBrowser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorIp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NewsId = 1,
                            VisitorBrowser = "Chrome",
                            VisitorCountry = "US",
                            VisitorIp = "123.456.789.0"
                        },
                        new
                        {
                            Id = 2,
                            NewsId = 1,
                            VisitorBrowser = "Opera",
                            VisitorCountry = "US",
                            VisitorIp = "133.446.799.1"
                        },
                        new
                        {
                            Id = 3,
                            NewsId = 2,
                            VisitorBrowser = "Mozilla Firefox",
                            VisitorCountry = "Canada",
                            VisitorIp = "333.126.439.5"
                        },
                        new
                        {
                            Id = 4,
                            NewsId = 2,
                            VisitorBrowser = "Chrome",
                            VisitorCountry = "France",
                            VisitorIp = "232.116.654.2"
                        },
                        new
                        {
                            Id = 5,
                            NewsId = 3,
                            VisitorBrowser = "Chrome",
                            VisitorCountry = "Ukraine",
                            VisitorIp = "196.226.743.0"
                        },
                        new
                        {
                            Id = 6,
                            NewsId = 5,
                            VisitorBrowser = "Opera",
                            VisitorCountry = "US",
                            VisitorIp = "133.446.799.1"
                        },
                        new
                        {
                            Id = 7,
                            NewsId = 4,
                            VisitorBrowser = "Mozilla Firefox",
                            VisitorCountry = "Canada",
                            VisitorIp = "333.126.439.5"
                        },
                        new
                        {
                            Id = 8,
                            NewsId = 6,
                            VisitorBrowser = "Chrome",
                            VisitorCountry = "France",
                            VisitorIp = "232.116.654.2"
                        });
                });

            modelBuilder.Entity("NewsApi.Core.Entities.News", b =>
                {
                    b.HasOne("NewsApi.Core.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsApi.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NewsApi.Core.Entities.Statistics", b =>
                {
                    b.HasOne("NewsApi.Core.Entities.News", "News")
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
